version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - --features=self_update
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    id: "uv-migrator"
    binary: uv-migrator

archives:
  - format: tar.gz
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}-{{ .Target }}
    builds:
      - uv-migrator

changelog:
  disable: true

release:
  footer: >-
    ---
    Released by [GoReleaser](https://
