version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - --features=self_update
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    id: "uv-migrator"
    binary: uv-migrator

  - builder: uv
    flags:
      - --offline
    id: "uv-migrator-pypi"
    buildmode: sdist
    tool: uv
    command: build

  - builder: uv
    flags:
      - --offline
    id: "uv-migrator-pypi-wheel"
    buildmode: wheel
    tool: uv
    command: build

archives:
  - formats: ["tar.gz"]
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}-{{ .Target }}
    ids:
      - uv-migrator

changelog:
  disable: true

release:
  footer: >-
    ---
    Released by [GoReleaser](https://
