version: 2
builds:
  - main: goreleaser.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: uv-migrator
    ignore:
      - goos: windows
        goarch: arm64
    hooks:
      post:
        - ./.goreleaser_hook.sh {{ .Arch }} {{ .Os }} {{ .ProjectName }}

changelog:
  disable: true

checksum:
  disable: true



