version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - -F self_update
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-
      {{- if eq .Os "darwin" }}x86_64-apple-darwin
      {{- else if and (eq .Os "linux") (eq .Arch "amd64") }}x86_64-unknown-linux-gnu
      {{- else if and (eq .Os "linux") (eq .Arch "arm64") }}aarch64-unknown-linux-gnu
      {{- else if and (eq .Os "darwin") (eq .Arch "arm64") }}aarch64-apple-darwin
      {{- else }}{{ .Os }}-{{ .Arch }}{{ end }}

changelog:
  disable: true

release:
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
