[package]
name = "uv-migrator"
version = "2024.5.0"
edition = "2021"
authors = ["stvnksslr@gmail.com"]
description = "Tool for converting various python package soltutions to use the uv solution by astral"
license = "MIT"
repository = "https://github.com/stvnksslr/uv-migrator"
readme = "README.md"
keywords = ["python", "uv"]

[dependencies]
clap = "4.5.20"
dirs = "5.0.1"
env_logger = "0.11.5"
log = "0.4.22"
self_update = "0.41.0"
serde = { version = "1.0.210" , features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
which = "6.0.3"

[dev-dependencies]
tempfile = "3.10.1"
