[package]
name = "uv-migrator"
version = "2024.3.1"
edition = "2021"
authors = ["stvnksslr@gmail.com"]
description = "Tool for converting various python package soltutions to use the uv solution by astral"
license = "MIT"
repository = "https://github.com/stvnksslr/uv-migrator"
readme = "README.md"
keywords = ["python", "uv"]

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.210" , features = ["derive"] }
toml = "0.8.19"
which = "6.0.3"
