[package]
name = "uv-migrator"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.210" , features = ["derive"] }
toml = "0.8.19"
which = "6.0.3"
